export function createApiClient(url='/api/data',{storage=globalThis.sessionStorage,transport=globalThis.fetch}={}){
 const key='smart-materials-session-v1';const session=()=>{try{return JSON.parse(storage.getItem(key)||'null')}catch{return null}};
 const call=async input=>{try{const r=await transport(url,{method:'POST',headers:{'Content-Type':'application/json',...(session()?.token?{Authorization:'Bearer '+session().token}:{})},signal:AbortSignal.timeout(45000),body:JSON.stringify({...input,request_id:crypto.randomUUID()})});const result=await r.json();if(!result.ok){if(r.status===401)storage.removeItem(key);throw Error(result.error||'บันทึกไม่สำเร็จ')}return {data:result.data,error:null}}catch(error){return {data:null,error:{message:error.message||'เชื่อมต่อเซิร์ฟเวอร์ไม่สำเร็จ'}}}};
 return {
  auth:{signInWithPassword:async credentials=>{const r=await call({action:'login',...credentials});if(!r.error)storage.setItem(key,JSON.stringify(r.data));return r},getSession:async()=>({data:{session:session()},error:null}),getUser:async()=>{if(!session())return {data:{user:null},error:null};const r=await call({action:'identity'});return {data:{user:r.data},error:r.error}},signOut:async()=>{const r=await call({action:'logout'});storage.removeItem(key);return r}},
  functions:{invoke:(_,{body})=>call({action:'manage-users',input:body})},rpc:(name,args)=>call({action:'movement',name,args}),correctMovement:input=>call({action:'correct-movement',...input}),
  from:table=>{const query={table,operation:'select',filters:[],orders:[]};let promise;const chain={select:columns=>{query.columns=columns;return chain},eq:(field,value)=>{query.filters.push({field,operator:'eq',value});return chain},in:(field,value)=>{query.filters.push({field,operator:'in',value});return chain},order:(field,{ascending=true}={})=>{query.orders.push({field,ascending});return chain},range:(a,b)=>{query.range=[a,b];return chain},limit:n=>{query.limit=n;return chain},single:()=>{query.single=true;return chain},maybeSingle:()=>{query.maybeSingle=true;return chain},upsert:value=>{query.operation='upsert';query.value=value;return chain},delete:()=>{query.operation='delete';return chain},then:(resolve,reject)=>{promise??=call({action:'query',query});return promise.then(resolve,reject)}};return chain}
 };
}
