import {canManageUsers,showUserManagement} from './user-management.js';
import {organization} from './organization.js';
import {logoUrl,loadBranding} from './branding.js';
import {printDocument} from './printing.js';
import './style.css';
import './responsive.css';
import './stock-template.css';
import {installUiIcons} from './ui-icons.js';
import {createIcons,icons} from 'lucide';
import {modules,csv} from './domain';
import {showMaterialReports} from './material-reports.js';
import {openEditor} from './editor.js';
import {openStock} from './stock.js';
import {auditHtml} from './audit-view.js';
import {openMaterialImport} from './material-import.js';
import {showMovements} from './movements.js';
import {loadSettings,showSettings} from './settings.js';
import {db,isDemo,enableDemo,list,save,remove,profile,movement,seedDemo,resetDemo,auditEntries} from './store';
const app=document.querySelector('#app');let rows=[],user=null,page='dashboard',query='',filter='',stockFilter='';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>Number(v||0).toLocaleString('th-TH',{minimumFractionDigits:2,maximumFractionDigits:2});
const icon=n=>`<i data-lucide="${n.replace(/([a-z0-9])([A-Z])/g,'$1-$2').toLowerCase()}" aria-hidden="true"></i>`;
function draw(html){app.innerHTML=html;createIcons({icons});}
function printRegistry(){
 const content=document.querySelector('#results').cloneNode(true);
 content.querySelectorAll('tr').forEach(row=>row.lastElementChild?.remove());
 const records=visible(),value=records.reduce((total,r)=>total+Number(r.amount)*Number(r.data.quantity||0),0);
 printDocument(`<h2>ทะเบียนวัสดุและมูลค่าคงเหลือ</h2><p>${esc(organization().name)}</p><p>${esc(organization().address)}</p><p>หมวด: ${esc(filter||'ทุกหมวด')} · คำค้น: ${esc(query||'ทั้งหมด')} · ยอดคงเหลือ: ${esc({empty:'หมดคลัง',low:'ถึงจุดสั่งซื้อ'}[stockFilter]||'ทั้งหมด')}</p><p>จำนวน ${records.length} รายการ · มูลค่าคงเหลือ ${money(value)} บาท · จัดทำเมื่อ ${esc(new Date().toLocaleString('th-TH'))}</p>${content.innerHTML}`,{className:'registry-print'});
}
const brand=()=>`<div class="brand"><img class="logo" data-logo="ministry" src="${logoUrl('ministry')}" alt="ตำแหน่งโลโก้กระทรวง"><img class="logo" data-logo="health_center" src="${logoUrl('health_center')}" alt="ตำแหน่งโลโก้ รพ.สต."><div>SMART วัสดุ<small data-org-name>${esc(organization().name)}</small></div></div>`;
function landing(){draw(`<header>${brand()}<button id="login">${icon('LogIn')} เข้าสู่ระบบ</button></header><section class="hero"><div><span class="eyebrow">MATERIALS • STOCK CARD</span><h1>จัดการวัสดุครบถ้วน<br>รู้ยอด รู้มูลค่า</h1><p>บันทึกรับ–จ่าย ติดตามยอดคงเหลือและมูลค่าวัสดุ<br>ตรวจสอบประวัติและออกรายงานจากข้อมูลที่จัดเก็บ<br>${esc(organization().name)}<br>${esc(organization().address)}</p><div class="actions"><button id="start">เข้าสู่ระบบงาน ${icon('ArrowUpRight')}</button><button class="secondary" id="demo">ทดลองใช้งาน</button></div><p class="muted" style="color:#cfbae5;margin-top:22px">ทะเบียนวัสดุ • รับวัสดุ • จ่ายวัสดุ • Stock Card • รายงาน</p></div><div class="visual"><div class="visual-card"><span class="eyebrow">MATERIALS MANAGEMENT</span><h2 style="margin-top:18px">วัสดุ</h2><div class="steps">${[['CalendarDays','01 · บันทึกทะเบียนวัสดุ'],['ClipboardCheck','02 · รับจ่ายและ Stock Card'],['Package','03 · ประวัติและยอดคงเหลือ'],['ListChecks','04 · คำนวณและออกรายงาน']].map(([i,t])=>`<div class="tile">${icon(i)}<span>${t}</span></div>`).join('')}</div><p style="margin:24px 0 0;font-size:12px">ข้อมูลชัดเจน · คำนวณมูลค่า · ตรวจสอบย้อนหลัง</p></div></div></section><section class="section"><span class="eyebrow" style="color:#8649be">MATERIALS • RECORDS • REPORTS</span><h2 style="margin-top:12px">บันทึกและรายงานวัสดุในที่เดียว</h2><div class="cards">${[["Package","ทะเบียนวัสดุ","จัดหมวด ค้นหารายการ และติดตามวัสดุถึงจุดสั่งซื้อ"],["ArrowLeftRight","รับ–จ่ายและ Stock Card","เลือกวันที่รับ–จ่าย ผู้ควบคุมวัสดุ ผู้รับ และคำนวณมูลค่า"],["ClipboardList","ตั้งค่ารายการ","จัดการผู้ควบคุมวัสดุ ผู้รับ หมวดวัสดุ และหน่วยนับ"],["ChartColumn","รายงานวัสดุ","สรุปยกมา รับ จ่าย คงเหลือตามช่วงวันที่ พร้อม CSV และ PDF"]].map(([i,t,d])=>`<div class="card">${icon(i)}<h3 style="font-size:16px">${t}</h3><p>${d}</p></div>`).join('')}</div></section><footer>ระบบคำนวณ จัดเก็บข้อมูล และรายงานวัสดุ</footer>`);document.querySelector('#login').onclick=login;document.querySelector('#start').onclick=login;document.querySelector('#demo').onclick=demo;}
function login(){draw(`<header>${brand()}<button id="back" class="secondary">หน้าหลัก</button></header><div class="login"><span class="eyebrow" style="color:#7540a8">STAFF ACCESS</span><h2 style="margin-top:15px">ยินดีต้อนรับกลับ</h2><p class="muted">เข้าสู่ระบบด้วยบัญชีเจ้าหน้าที่</p><form id="loginForm"><label>ID / อีเมล<input type="text" maxlength="254" name="email" autocomplete="username" required></label><label>รหัสผ่าน<input type="password" name="password" autocomplete="current-password" required minlength="8"></label><div id="error" class="error" role="alert"></div><button ${db?'':'disabled'}>เข้าสู่ระบบ</button></form>${db?'':'<p class="banner">ยังไม่ได้ตั้งค่าเซิร์ฟเวอร์ MongoDB ดูขั้นตอนใน README.md</p>'}<button id="demo" class="secondary">ทดลองด้วยข้อมูลตัวอย่าง</button><p class="muted">บัญชีเจ้าหน้าที่สร้างและกำหนดสิทธิ์โดยผู้ดูแลระบบ</p></div>`);document.querySelector('#back').onclick=landing;document.querySelector('#demo').onclick=demo;document.querySelector('#loginForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),btn=e.target.querySelector('button');btn.disabled=true;btn.textContent='กำลังเข้าสู่ระบบ...';document.querySelector('#error').textContent='กำลังตรวจสอบบัญชี กรุณารอสักครู่';try{const {error}=await db.auth.signInWithPassword({email:f.get('email'),password:f.get('password')});if(error)throw error;document.querySelector('#error').textContent='ตรวจสอบบัญชีผ่านแล้ว กำลังโหลดข้อมูล';await load()}catch(err){const target=document.querySelector('#error');if(target)target.textContent=err.message||'เข้าสู่ระบบไม่สำเร็จ';else alert(err.message||'โหลดข้อมูลไม่สำเร็จ')}finally{btn.disabled=false;btn.textContent='เข้าสู่ระบบ'}};}
async function demo(){await action(async()=>{enableDemo();await seedDemo();await load();});}
async function load(){user=await profile();if(!user)return login();rows=await list();await loadSettings(rows);await loadBranding();render();}
function shell(content){draw(`<div class="shell"><aside>${brand()}<nav><button data-page="dashboard" class="${page==='dashboard'?'active':''}">${icon('LayoutDashboard')} ภาพรวม</button>${Object.entries(modules).map(([k,[t,i]])=>`<button data-page="${k}" class="${page===k?'active':''}">${icon(i)} ${t}</button>`).join('')}<button data-page="receipts">${icon('PackagePlus')} รับวัสดุ</button><button data-page="issues">${icon('PackageMinus')} จ่ายวัสดุ</button><button data-page="reports">${icon('ChartColumn')} รายงาน</button><button data-page="audit">${icon('History')} ประวัติการทำรายการ</button><button data-page="settings">${icon('Settings')} ตั้งค่า</button>${canManageUsers(user)?`<button data-page="users">${icon('UsersRound')} จัดการผู้ใช้</button>`:''}</nav></aside><main><div class="top"><div><h2>${page==='dashboard'?'ภาพรวมวัสดุ':page==='receipts'?'รับวัสดุ':page==='issues'?'จ่ายวัสดุ':page==='reports'?'รายงานวัสดุ':page==='settings'?'ตั้งค่ารายการ':page==='audit'?'ประวัติการทำรายการ':page==='users'?'จัดการผู้ใช้':modules[page][0]}</h2><span class="muted">${esc(user.full_name||'เจ้าหน้าที่')} · ${esc({admin:'ผู้ดูแลระบบ',officer:'เจ้าหน้าที่',viewer:'ผู้ดูข้อมูล',approver:'ผู้ดูข้อมูล'}[user.role]||user.role)}</span></div><button id="logout" class="secondary">${icon('LogOut')} ออกจากระบบ</button></div>${isDemo()?'<div class="banner">โหมดทดลอง — ข้อมูลสมมติในเบราว์เซอร์นี้ <button id="resetDemo" class="secondary" style="margin-left:12px">รีเซ็ตตัวอย่าง</button></div>':''}${content}<dialog id="editor"></dialog></main></div>`);document.querySelector('#resetDemo')?.addEventListener('click',()=>action(async()=>{await resetDemo();await load()}));document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;query='';filter='';stockFilter='';render()});document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));document.querySelector('#logout').onclick=async()=>{if(isDemo())location.reload();else{await db.auth.signOut();user=null;landing()}};}
function render(){if(page==='dashboard')dashboard();else if(page==='receipts'||page==='issues')showMovements({rows,user,shell,onReload:load,direction:page==='receipts'?1:-1});else if(page==='reports')reports();else if(page==='settings')showSettings({shell,user});else if(page==='users'){if(canManageUsers(user))showUserManagement({shell,user});else{page='dashboard';dashboard()}}else if(page==='audit')audit();else registry();}
function dashboard(){const materials=rows.filter(r=>r.module==='materials'),low=materials.filter(r=>Number(r.data.quantity)<=Number(r.data.minimum));shell(`<div class="stats">${[['วัสดุ',materials.length+' รายการ'],['วัสดุหมดคลัง',materials.filter(r=>Number(r.data.quantity||0)===0).length+' รายการ'],['มูลค่าวัสดุคงเหลือ',money(materials.reduce((sum,r)=>sum+Number(r.amount)*Number(r.data.quantity||0),0))+' บาท'],['วัสดุถึงจุดสั่งซื้อ',low.length+' รายการ']].map(([t,v])=>`<div class="stat"><span class="muted">${t}</span><strong style="font-size:24px">${v}</strong></div>`).join('')}</div><div class="report"><h3>วัสดุถึงจุดสั่งซื้อ</h3>${low.map(r=>`<p>${esc(r.title)} <span class="badge">คงเหลือ ${esc(r.data.quantity)} ${esc(r.data.unit)}</span></p>`).join('')||'<p class="muted">ไม่มีวัสดุถึงจุดสั่งซื้อ</p>'}</div><h3>วัสดุแยกตามหมวด</h3><div class="cards">${[...new Set(materials.map(r=>r.data.group||'ไม่ระบุหมวด'))].map(group=>{const n=materials.filter(r=>(r.data.group||'ไม่ระบุหมวด')===group).length;return `<div class="card">${icon('Package')}<h3>${esc(group)}</h3><p>${n} รายการ</p><div class="chart"><span style="width:${materials.length?n/materials.length*100:0}%"></span></div></div>`}).join('')}</div>`);}
function visible(){return rows.filter(r=>r.module===page&&(!filter||r.data.group===filter)&&(!stockFilter||(stockFilter==='empty'?Number(r.data.quantity||0)===0:Number(r.data.quantity||0)<=Number(r.data.minimum||0)))&&`${r.title} ${r.code} ${r.data.group||''}`.toLowerCase().includes(query.toLowerCase()))}
function registry(){shell(`<div class="toolbar"><input id="search" aria-label="ค้นหา" placeholder="ค้นหารหัส ชื่อ หรือหมวดวัสดุ" value="${esc(query)}">${['admin','officer'].includes(user.role)?'<button id="add">+ เพิ่มวัสดุ</button><button id="importMaterials" class="secondary">นำเข้า CSV</button>':''}<select id="groupFilter"><option value="">ทุกหมวด</option>${[...new Set(rows.map(r=>r.data.group).filter(Boolean))].map(g=>`<option value="${esc(g)}" ${filter===g?'selected':''}>${esc(g)}</option>`).join('')}</select><select id="stockFilter"><option value="">ทุกยอดคงเหลือ</option><option value="empty">หมดคลัง</option><option value="low">ถึงจุดสั่งซื้อ</option></select><button id="export" class="secondary">ส่งออก CSV</button><button id="print" class="secondary">พิมพ์ / PDF</button></div><div id="results"></div>`);table();document.querySelector('#importMaterials')?.addEventListener('click',()=>openMaterialImport({rows,onReload:load}));document.querySelector('#groupFilter').onchange=e=>{filter=e.target.value;table()};document.querySelector('#stockFilter').value=stockFilter;document.querySelector('#stockFilter').onchange=e=>{stockFilter=e.target.value;table()};document.querySelector('#search').oninput=e=>{query=e.target.value;table()};document.querySelector('#add')?.addEventListener('click',()=>edit());document.querySelector('#print').onclick=()=>printRegistry();document.querySelector('#export').onclick=()=>download(csv([['รหัส','รายการ','หมวด','หน่วย','ราคาต่อหน่วย','คงเหลือ','มูลค่าคงเหลือ'],...visible().map(r=>[r.code,r.title,r.data.group,r.data.unit,r.amount,r.data.quantity,Number(r.amount)*Number(r.data.quantity||0)])]),`${page}.csv`);}
function table(){document.querySelector('#results').innerHTML=`<div class="tablewrap"><table><thead><tr><th>รหัสวัสดุ</th><th>ชื่อวัสดุ / หมวด</th><th>ราคาต่อหน่วย (บาท)</th>${page==='materials'?'<th>คงเหลือ</th><th>มูลค่าคงเหลือ (บาท)</th>':''}<th>จัดการ</th></tr></thead><tbody>${visible().map(r=>`<tr><td>${esc(r.code)}</td><td>${esc(r.title)}<br><span class="muted">${esc(r.data.group||'ยังไม่ระบุหมวด')}</span></td><td>${money(r.amount)}</td>${page==='materials'?`<td>${esc(r.data.quantity||0)} ${esc(r.data.unit)}</td><td>${money(Number(r.amount)*Number(r.data.quantity||0))}</td>`:''}<td><button data-edit="${r.id}" class="secondary">รายละเอียด</button>${page==='materials'?`<button data-ledger="${r.id}" class="secondary">Stock Card</button>`:''}${['admin','officer'].includes(user.role)&&page==='materials'?`<button data-stock="${r.id}" class="secondary">รับวัสดุ</button><button data-issue="${r.id}" class="secondary">จ่ายวัสดุ</button>`:''}${user.role==='admin'&&r.module!=='materials'?`<button data-delete="${r.id}" class="danger">ลบ</button>`:''}</td></tr>`).join('')}</tbody></table>${visible().length?'':'<div class="empty">ยังไม่มีรายการตามตัวกรอง</div>'}</div>`;document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(rows.find(r=>r.id===b.dataset.edit)));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{if(confirm('ยืนยันลบรายการนี้?'))await action(async()=>{await remove(b.dataset.delete);await load()})});document.querySelectorAll('[data-ledger]').forEach(b=>b.onclick=()=>stock(rows.find(r=>r.id===b.dataset.ledger),true));document.querySelectorAll('[data-stock]').forEach(b=>b.onclick=()=>{page='receipts';showMovements({rows,user,shell,onReload:load,initialRecord:rows.find(r=>r.id===b.dataset.stock)})});document.querySelectorAll('[data-issue]').forEach(b=>b.onclick=()=>{page='issues';showMovements({rows,user,shell,onReload:load,direction:-1,initialRecord:rows.find(r=>r.id===b.dataset.issue)})});}
function edit(r){openEditor({record:r,page,rows,user,onReload:load,onNavigate:record=>{page=record.module;query='';filter='';render();edit(record)}})}
function stock(r,readOnly=false){openStock(r,load,readOnly)}
function reports(){showMaterialReports({rows,shell})}
async function audit(){
 shell('<div class="toolbar"><input id="auditSearch" type="search" placeholder="ค้นหารหัสหรือชื่อวัสดุ" aria-label="ค้นหาประวัติ"></div><div id="auditResults" class="report">กำลังโหลด...</div>');
 const target=document.querySelector('#auditResults'),search=document.querySelector('#auditSearch');
 await action(async()=>{const data=await auditEntries();if(!target.isConnected)return;const drawHistory=()=>{const terms=search.value.trim().toLowerCase().split(/\s+/).filter(Boolean),filtered=data.filter(e=>{const r=e.new_data||e.old_data||{};return terms.every(t=>`${r.code} ${r.title}`.toLowerCase().includes(t))});target.innerHTML='<p class="muted">ค้นหาใน 200 รายการล่าสุด · เปิดรายการเพื่อดูข้อมูลก่อนและหลังแก้ไข</p>'+auditHtml(filtered)};search.oninput=drawHistory;drawHistory()});
}
async function action(fn,target){try{await fn()}catch(e){if(target)document.querySelector(target).textContent=e.message;else alert(e.message)}}
function download(content,name){const url=URL.createObjectURL(new Blob([content],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
installUiIcons(app);landing();if(db)db.auth.getSession().then(({data})=>{if(data.session)action(load)});
