import {save} from './store.js';
import {csv} from './domain.js';
import {parseMaterialCsv,materialCsvColumns as columns} from './material-csv.js';
import {settingValues} from './settings.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function openMaterialImport({rows,onReload}){
 const d=document.querySelector('#editor');let pending=[],finished=0;
 d.innerHTML='<h2>นำเข้าทะเบียนวัสดุ</h2><p class="muted">นำเข้ารายการใหม่จาก CSV ยอดเริ่มต้นเป็นศูนย์ แล้วบันทึกรับเข้าที่หน้ารับวัสดุเพื่อสร้างประวัติและยอดคงเหลือ</p><button id="importTemplate" class="secondary">ดาวน์โหลดไฟล์ตัวอย่าง</button><p><input id="importFile" type="file" accept=".csv,text/csv" aria-label="ไฟล์ทะเบียนวัสดุ CSV"></p><div id="importPreview"></div><p id="importError" class="error" role="alert"></p><div class="modal-actions"><button id="importClose" class="secondary">ปิด</button><button id="importSave" disabled>นำเข้ารายการ</button></div>';d.showModal();
 const button=d.querySelector('#importSave'),file=d.querySelector('#importFile');d.querySelector('#importClose').onclick=()=>d.close();
 d.querySelector('#importTemplate').onclick=()=>{const url=URL.createObjectURL(new Blob([csv([columns,['IMPORT-EXAMPLE-001','แฟ้มเอกสารตัวอย่าง','วัสดุสำนักงาน','ชิ้น',35,10,'ห้องธุรการ'],['IMPORT-EXAMPLE-002','สายต่อ USB ตัวอย่าง','วัสดุคอมพิวเตอร์','ชิ้น',120,2,'ห้องเก็บวัสดุทั่วไป'],['IMPORT-EXAMPLE-003','แผ่นพับตัวอย่าง','วัสดุประชาสัมพันธ์','แผ่น',0,20,'ห้องเก็บวัสดุทั่วไป']])],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='material-import-template.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 file.onchange=async()=>{button.disabled=true;pending=[];finished=0;d.querySelector('#importPreview').textContent='';d.querySelector('#importError').textContent='';try{const input=file.files[0];if(!input)return;if(input.size>2000000)throw Error('ไฟล์ต้องไม่เกิน 2 MB');pending=parseMaterialCsv(await input.text());if(!pending.length||pending.length>1000)throw Error('นำเข้าได้ 1–1,000 รายการต่อครั้ง');const codes=new Set(rows.map(r=>r.code));const groups=settingValues('groups'),units=settingValues('units');for(const r of pending){if(!groups.includes(r.data.group))throw Error(`หมวด "${r.data.group}" ยังไม่ได้ตั้งค่าหรือปิดใช้งาน กรุณาเพิ่มในตั้งค่าก่อนนำเข้า`);if(!units.includes(r.data.unit))throw Error(`หน่วย "${r.data.unit}" ยังไม่ได้ตั้งค่าหรือปิดใช้งาน กรุณาเพิ่มในตั้งค่าก่อนนำเข้า`);}for(const r of pending){if(codes.has(r.code))throw Error(`รหัส ${r.code} ซ้ำ กรุณาใช้รับเข้าแทนการเพิ่มทะเบียนซ้ำ`);codes.add(r.code)}d.querySelector('#importPreview').innerHTML=`<p>พร้อมนำเข้า ${pending.length} รายการ</p><div class="tablewrap"><table><tbody>${pending.map(r=>`<tr><td>${esc(r.code)}</td><td>${esc(r.title)}</td><td>${esc(r.data.unit)}</td><td>${esc(r.amount)}</td></tr>`).join('')}</tbody></table></div>`;button.disabled=false}catch(e){d.querySelector('#importError').textContent=e.message}};
 button.onclick=async()=>{button.disabled=true;file.disabled=true;d.querySelector('#importClose').disabled=true;try{while(finished<pending.length){await save(pending[finished]);finished++}d.close();await onReload()}catch(e){d.querySelector('#importError').textContent=`นำเข้าสำเร็จ ${finished}/${pending.length} รายการ: ${e.message} กดนำเข้าอีกครั้งเพื่อทำรายการที่เหลือ`;button.disabled=false}finally{file.disabled=false;d.querySelector('#importClose').disabled=false}};
}
